// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package server

import (
	"github.com/schwarzeni/Go-000/Week04/internal/app/myapp/dao"
	"github.com/schwarzeni/Go-000/Week04/internal/app/myapp/service"
	"github.com/schwarzeni/Go-000/Week04/pkg/db"
)

// Injectors from wire.go:

func NewServerWithWire(svcConfig *HTTPServerConfig, dbConfig *db.DBConfig) (*HTTPServer, error) {
	gormDB, err := db.NewGorm(dbConfig)
	if err != nil {
		return nil, err
	}
	daoDao, err := dao.NewDao(gormDB)
	if err != nil {
		return nil, err
	}
	serviceService := service.NewService(daoDao)
	handler := NewHandler(serviceService)
	httpServer := NewHTTPServer(svcConfig, handler)
	return httpServer, nil
}
